-- =============================================
-- ESQUEMA DE BASE DE DATOS - CAFEGO
-- Generado para PostgreSQL
-- =============================================

-- 1. Tabla de USUARIOS (Clientes)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 2. Tabla de PRODUCTOS
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL,
    stock INTEGER NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 3. Tabla de ETIQUETAS (Tags)
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 4. Tabla Intermedia PRODUCTOS_TAGS (Muchos a Muchos)
CREATE TABLE IF NOT EXISTS product_tags (
    product_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, tag_id)
);

-- 5. Tabla de FACTURAS (Cabecera)
CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDIENTE',
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- 6. Tabla de DETALLES DE FACTURA (Items)
CREATE TABLE IF NOT EXISTS invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- =============================================
-- RELACIONES (FOREIGN KEYS)
-- =============================================

-- Relación: Factura pertenece a Usuario
ALTER TABLE invoices
    ADD CONSTRAINT fk_invoices_user 
    FOREIGN KEY (user_id) REFERENCES users (id);

-- Relación: Detalle pertenece a Factura
ALTER TABLE invoice_details
    ADD CONSTRAINT fk_details_invoice 
    FOREIGN KEY (invoice_id) REFERENCES invoices (id);

-- Relación: Detalle refiere a un Producto
ALTER TABLE invoice_details
    ADD CONSTRAINT fk_details_product 
    FOREIGN KEY (product_id) REFERENCES products (id);

-- Relaciones de la tabla intermedia (Tags)
ALTER TABLE product_tags
    ADD CONSTRAINT fk_product_tags_product 
    FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_tags
    ADD CONSTRAINT fk_product_tags_tag 
    FOREIGN KEY (tag_id) REFERENCES tags (id);